// Source-locked snapshot for research and parity auditing.
// Original author: JS_TechTrading
// Original script: JS-TechTrading: Supertrend-Strategy_Basic version
// Source mirror commit: hasnocool/tradingview-pine-scripts@69969aeaf271b2f7b5a7632a1bde43069a0cbe26
// Original license: Mozilla Public License 2.0

//@version=5
strategy("Supertrend", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=1, process_orders_on_close=false)

var string group_text000="Choose Strategy"
var string group_text0="Supertrend Settings"
var string group_text0000="Ema Settings"
var string group_text00="Rsi Settings"
var string group_text1="Backtest Period"
var string group_text2="Trade Direction"
var string group_text4="Sl/Tp Settings"

option_ch=input.string('Pullback', title="Type Of Strategy", options=['Pullback','Simple'])
atrPeriod=input(10, "ATR Length", group=group_text0)
factor=input.float(3.0, "Factor", step=0.01, group=group_text0)
[supertrend, direction]=ta.supertrend(factor, atrPeriod)
bodyMiddle=plot((open+close)/2, display=display.none)
upTrend=plot(direction<0 ? supertrend : na, "Up Trend", color=color.green, style=plot.style_linebr)
downTrend=plot(direction<0 ? na : supertrend, "Down Trend", color=color.red, style=plot.style_linebr)
fill(bodyMiddle, upTrend, color.new(color.green,90), fillgaps=false)
fill(bodyMiddle, downTrend, color.new(color.red,90), fillgaps=false)
long=direction<0 ? supertrend : na
short=direction<0 ? na : supertrend
longpos=false
shortpos=false
longpos:=long ? true : short ? false : longpos[1]
shortpos:=short ? true : long ? false : shortpos[1]
fin_pullbuy=(ta.crossunder(low[1],long) and long and high>high[1])
fin_pullsell=(ta.crossover(high[1],short) and short and low<low[1])

on_ma=input.bool(true,"Ema Condition On/Off",group=group_text0000)
ma_len=input.int(200,minval=1,title="Ema Length",group=group_text0000)
ma_src=input.source(close,title="Ema Source",group=group_text0000)
ma_out=ta.ema(ma_src,ma_len)
ma_buy=on_ma ? close>ma_out ? true:false:true
ma_sell=on_ma ? close<ma_out ? true:false:true

en_rsi=input.bool(true,"Rsi Condition On/Off",group=group_text00)
rsiSource=input(title='RSI Source',defval=close,group=group_text00)
rsiLength=input(title='RSI Length',defval=14,group=group_text00)
rsiOverbought=input(title='RSI BUY Level',defval=50,group=group_text00)
rsiOversold=input(title='RSI SELL Level',defval=50,group=group_text00)
rsiValue=ta.rsi(rsiSource,rsiLength)
rsi_buy=en_rsi ? rsiValue>=rsiOverbought ? true:false:true
rsi_sell=en_rsi ? rsiValue<=rsiOversold ? true:false:true

buy_cond=option_ch=='Simple' ? long and not(longpos[1]) and rsi_buy and ma_buy : option_ch=='Pullback' ? fin_pullbuy and rsi_buy and ma_buy : na
sell_cond=option_ch=='Simple' ? short and not(shortpos[1]) and rsi_sell and ma_sell : option_ch=='Pullback' ? fin_pullsell and rsi_sell and ma_sell : na

start=input.time(timestamp('2005-01-01'),title='Start calculations from',group=group_text1)
end=input.time(timestamp('2045-03-01'),title='End calculations',group=group_text1)
time_cond=time>=start and time<=end
tradeDirection=input.string(title='Trade Direction',options=['Long','Short','Both'],defval='Both',group=group_text2)
longOK=(tradeDirection=='Long') or (tradeDirection=='Both')
shortOK=(tradeDirection=='Short') or (tradeDirection=='Both')

if buy_cond and longOK and time_cond and strategy.position_size==0
    strategy.entry('long',direction=strategy.long)
if sell_cond and shortOK and time_cond and strategy.position_size==0
    strategy.entry('short',direction=strategy.short)

stopPer=input.float(1.0,step=0.10,title='Stop Loss %',group=group_text4)/100
takePer=input.float(1.0,step=0.10,title='Take Profit %',group=group_text4)/100
longStop=strategy.position_avg_price*(1-stopPer)
shortStop=strategy.position_avg_price*(1+stopPer)
shortTake=strategy.position_avg_price*(1-takePer)
longTake=strategy.position_avg_price*(1+takePer)
if strategy.position_size>0
    strategy.exit(id='Close Long',stop=longStop,limit=longTake)
if strategy.position_size<0
    strategy.exit(id='Close Short',stop=shortStop,limit=shortTake)

plot(strategy.position_size>0 ? longStop:na,style=plot.style_linebr,color=color.new(color.red,0),linewidth=1,title='Long Fixed SL')
plot(strategy.position_size<0 ? shortStop:na,style=plot.style_linebr,color=color.new(color.red,0),linewidth=1,title='Short Fixed SL')
plot(strategy.position_size>0 ? longTake:na,style=plot.style_linebr,color=color.new(color.green,0),linewidth=1,title='Long Take Profit')
plot(strategy.position_size<0 ? shortTake:na,style=plot.style_linebr,color=color.new(color.green,0),linewidth=1,title='Short Take Profit')
