from __future__ import annotations

from types import MappingProxyType
from typing import Mapping

from .types import EntryStyle, HoldHorizon, MethodProfile, MethodSubtype, RiskMode, TradeMethod


def _profile(*, method: TradeMethod, subtype: MethodSubtype, version: str, label: str, entry_style: EntryStyle, hold_horizon: HoldHorizon, risk_mode: RiskMode, target_r: float, stop_r: float, time_stop_seconds: int, size_multiplier: float, overlays: tuple[str, ...], min_net_edge_bps: float, safety_margin_bps: float, max_spread_bps: float, min_depth_ratio: float, vol_range: tuple[float, float], atr_range: tuple[float, float], regimes: tuple[str, ...], max_signal_age_seconds: int, max_position_size_pct: float, max_leverage: float, max_dd_day_pct: float, max_dd_total_pct: float, min_liq_buffer_pct: float) -> MethodProfile:
    return MethodProfile(method=method, method_subtype=subtype, profile_version=version, label=label, entry_style=entry_style, hold_horizon=hold_horizon, risk_mode=risk_mode, target_r=target_r, stop_r=stop_r, time_stop_seconds=time_stop_seconds, size_multiplier=size_multiplier, execution_overlays=overlays, min_net_edge_bps=min_net_edge_bps, safety_margin_bps=safety_margin_bps, max_spread_bps=max_spread_bps, min_depth_ratio=min_depth_ratio, min_realized_vol_bps=vol_range[0], max_realized_vol_bps=vol_range[1], min_atr_bps=atr_range[0], max_atr_bps=atr_range[1], allowed_regimes=regimes, max_signal_age_seconds=max_signal_age_seconds, max_position_size_pct=max_position_size_pct, max_leverage=max_leverage, max_dd_day_pct=max_dd_day_pct, max_dd_total_pct=max_dd_total_pct, min_liq_buffer_pct=min_liq_buffer_pct)


_PROFILES: dict[tuple[TradeMethod, MethodSubtype], MethodProfile] = {
    (TradeMethod.SCALP_FIRST, MethodSubtype.REVERT): _profile(method=TradeMethod.SCALP_FIRST, subtype=MethodSubtype.REVERT, version="1.0.0-candidate", label="Scalp-first · Revert", entry_style=EntryStyle.PULLBACK_CONFIRM, hold_horizon=HoldHorizon.M3_15, risk_mode=RiskMode.TIGHT, target_r=1.25, stop_r=-0.75, time_stop_seconds=900, size_multiplier=0.70, overlays=("post_only_preferred", "spread_guard", "time_stop", "single_entry"), min_net_edge_bps=8.0, safety_margin_bps=3.0, max_spread_bps=4.0, min_depth_ratio=8.0, vol_range=(8.0, 120.0), atr_range=(6.0, 140.0), regimes=("range", "mean_revert", "liquidity_reversion"), max_signal_age_seconds=90, max_position_size_pct=10.0, max_leverage=15.0, max_dd_day_pct=3.0, max_dd_total_pct=8.0, min_liq_buffer_pct=25.0),
    (TradeMethod.SCALP_FIRST, MethodSubtype.CONTINUATION): _profile(method=TradeMethod.SCALP_FIRST, subtype=MethodSubtype.CONTINUATION, version="1.0.0-candidate", label="Scalp-first · Continuation", entry_style=EntryStyle.BREAK_RECLAIM, hold_horizon=HoldHorizon.M3_15, risk_mode=RiskMode.TIGHT, target_r=1.50, stop_r=-0.75, time_stop_seconds=900, size_multiplier=0.75, overlays=("reclaim_confirm", "spread_guard", "time_stop", "partial30_optional"), min_net_edge_bps=9.0, safety_margin_bps=3.0, max_spread_bps=4.5, min_depth_ratio=9.0, vol_range=(12.0, 160.0), atr_range=(8.0, 180.0), regimes=("trend", "breakout", "expansion"), max_signal_age_seconds=75, max_position_size_pct=10.0, max_leverage=15.0, max_dd_day_pct=3.0, max_dd_total_pct=8.0, min_liq_buffer_pct=25.0),
    (TradeMethod.SCALP_FIRST, MethodSubtype.LIQUIDITY_RECLAIM): _profile(method=TradeMethod.SCALP_FIRST, subtype=MethodSubtype.LIQUIDITY_RECLAIM, version="1.0.0-candidate", label="Scalp-first · Liquidity Reclaim", entry_style=EntryStyle.BREAK_RECLAIM, hold_horizon=HoldHorizon.M3_15, risk_mode=RiskMode.TIGHT, target_r=1.65, stop_r=-0.75, time_stop_seconds=900, size_multiplier=0.70, overlays=("sweep_required", "reclaim_close_required", "spread_guard", "time_stop"), min_net_edge_bps=10.0, safety_margin_bps=3.5, max_spread_bps=4.0, min_depth_ratio=10.0, vol_range=(10.0, 180.0), atr_range=(8.0, 200.0), regimes=("liquidity_sweep", "stop_run", "reclaim"), max_signal_age_seconds=60, max_position_size_pct=10.0, max_leverage=15.0, max_dd_day_pct=3.0, max_dd_total_pct=8.0, min_liq_buffer_pct=27.5),
    (TradeMethod.INTRADAY, MethodSubtype.BREAKOUT_PROBE): _profile(method=TradeMethod.INTRADAY, subtype=MethodSubtype.BREAKOUT_PROBE, version="1.0.0-candidate", label="Intraday · Breakout Probe", entry_style=EntryStyle.OBSERVE_THEN_CONFIRM, hold_horizon=HoldHorizon.M10_45, risk_mode=RiskMode.BALANCED, target_r=2.00, stop_r=-0.75, time_stop_seconds=2700, size_multiplier=0.80, overlays=("breakout_confirm", "retest_preferred", "partial30_optional", "mfe_runner_optional"), min_net_edge_bps=12.0, safety_margin_bps=4.0, max_spread_bps=6.0, min_depth_ratio=7.0, vol_range=(10.0, 220.0), atr_range=(8.0, 240.0), regimes=("trend", "breakout", "expansion"), max_signal_age_seconds=180, max_position_size_pct=15.0, max_leverage=20.0, max_dd_day_pct=4.0, max_dd_total_pct=10.0, min_liq_buffer_pct=22.5),
    (TradeMethod.INTRADAY, MethodSubtype.RESCUE): _profile(method=TradeMethod.INTRADAY, subtype=MethodSubtype.RESCUE, version="1.0.0-candidate", label="Intraday · Rescue", entry_style=EntryStyle.OBSERVE_THEN_CONFIRM, hold_horizon=HoldHorizon.M10_45, risk_mode=RiskMode.DEFENSIVE, target_r=1.00, stop_r=-0.50, time_stop_seconds=1800, size_multiplier=0.35, overlays=("observe_first", "no_average_down", "reduce_only_exit", "time_stop"), min_net_edge_bps=14.0, safety_margin_bps=5.0, max_spread_bps=5.0, min_depth_ratio=12.0, vol_range=(6.0, 150.0), atr_range=(5.0, 160.0), regimes=("repairable_dislocation", "failed_breakout", "range"), max_signal_age_seconds=120, max_position_size_pct=5.0, max_leverage=10.0, max_dd_day_pct=2.0, max_dd_total_pct=6.0, min_liq_buffer_pct=35.0),
    (TradeMethod.TACTICAL_SWING, MethodSubtype.CONTINUATION): _profile(method=TradeMethod.TACTICAL_SWING, subtype=MethodSubtype.CONTINUATION, version="1.0.0-candidate", label="Tactical Swing · Continuation", entry_style=EntryStyle.PULLBACK_CONFIRM, hold_horizon=HoldHorizon.H2_6, risk_mode=RiskMode.BALANCED, target_r=2.50, stop_r=-0.75, time_stop_seconds=21600, size_multiplier=0.85, overlays=("htf_alignment", "pullback_confirm", "partial30_optional", "mfe_runner_optional"), min_net_edge_bps=18.0, safety_margin_bps=5.0, max_spread_bps=8.0, min_depth_ratio=6.0, vol_range=(6.0, 260.0), atr_range=(8.0, 300.0), regimes=("trend", "persistent_trend", "expansion"), max_signal_age_seconds=900, max_position_size_pct=15.0, max_leverage=15.0, max_dd_day_pct=4.0, max_dd_total_pct=10.0, min_liq_buffer_pct=25.0),
}

METHOD_PROFILES: Mapping[tuple[TradeMethod, MethodSubtype], MethodProfile] = MappingProxyType(_PROFILES)


def get_profile(method: TradeMethod, subtype: MethodSubtype) -> MethodProfile | None:
    return METHOD_PROFILES.get((method, subtype))
