from __future__ import annotations

TEAM_CONFIGS = {
    "ALPHA": {
        "schema_version": "1.6.7",
        "profile_id": "alpha-primary-trend",
        "name": "ALPHA",
        "lead": "LBot",
        "support": "MBot",
        "conditional_helper": "OBot",
        "watchers": ["regime", "risk_decay", "venue", "consensus"],
        "team_runtime_policy": {
            "market_regime_gate": {"allow": ["trend", "breakout", "range", "mean_revert", "risk_off", "unknown"]},
            "fusion_rules": {"helper_on_breakout": True, "helper_on_high_fit": True, "veto": True, "boost_penalty": True, "handoff": True},
            "penalty_boost_rules": {"venue_weak_penalty": True, "consensus_low_penalty": True, "drawdown_penalty": True},
            "boost_rules": {"trend_confirm_boost": 0.04},
            "watcher_weight": {"regime": 1.0, "risk_decay": 1.0, "venue": 1.0, "consensus": 0.8},
            "helper_pack": {"enabled": True, "helper_only_if_triggered": True},
            "freeze_mode": {"veto": True},
            "lead_execution_authority": True,
        },
    },
    "BETA": {
        "schema_version": "1.6.7",
        "profile_id": "beta-mean-revert",
        "name": "BETA",
        "lead": "MBot",
        "support": "LBot",
        "conditional_helper": "SBot",
        "watchers": ["regime", "risk_decay", "venue", "consensus"],
        "team_runtime_policy": {
            "market_regime_gate": {"allow": ["range", "mean_revert", "trend", "unknown"]},
            "fusion_rules": {"helper_on_breakout": False, "helper_on_high_fit": True, "veto": True, "boost_penalty": True, "handoff": True},
            "penalty_boost_rules": {"venue_weak_penalty": True, "consensus_low_penalty": True, "drawdown_penalty": True},
            "boost_rules": {"trend_confirm_boost": 0.02},
            "watcher_weight": {"regime": 1.0, "risk_decay": 1.2, "venue": 1.0, "consensus": 0.8},
            "helper_pack": {"enabled": True, "helper_only_if_triggered": True},
            "freeze_mode": {"veto": True},
            "lead_execution_authority": True,
        },
    },
    "GAMMA": {
        "schema_version": "1.6.7",
        "profile_id": "gamma-breakout",
        "name": "GAMMA",
        "lead": "OBot",
        "support": "SBot",
        "conditional_helper": "MBot",
        "watchers": ["regime", "risk_decay", "venue", "consensus"],
        "team_runtime_policy": {
            "market_regime_gate": {"allow": ["breakout", "trend", "unknown"]},
            "fusion_rules": {"helper_on_breakout": True, "helper_on_high_fit": True, "veto": True, "boost_penalty": True, "handoff": True},
            "penalty_boost_rules": {"venue_weak_penalty": True, "consensus_low_penalty": True, "drawdown_penalty": True},
            "boost_rules": {"trend_confirm_boost": 0.03},
            "watcher_weight": {"regime": 1.1, "risk_decay": 1.0, "venue": 1.1, "consensus": 0.7},
            "helper_pack": {"enabled": True, "helper_only_if_triggered": True},
            "freeze_mode": {"veto": True},
            "lead_execution_authority": True,
        },
    },
    "DELTA": {
        "schema_version": "1.6.7",
        "profile_id": "delta-defensive",
        "name": "DELTA",
        "lead": "SBot",
        "support": "OBot",
        "conditional_helper": "LBot",
        "watchers": ["regime", "risk_decay", "venue", "consensus"],
        "team_runtime_policy": {
            "market_regime_gate": {"allow": ["risk_off", "defensive", "chop", "unknown", "trend"]},
            "fusion_rules": {"helper_on_breakout": False, "helper_on_high_fit": False, "veto": True, "boost_penalty": True, "handoff": True},
            "penalty_boost_rules": {"venue_weak_penalty": True, "consensus_low_penalty": True, "drawdown_penalty": True},
            "boost_rules": {"trend_confirm_boost": 0.00},
            "watcher_weight": {"regime": 0.9, "risk_decay": 1.3, "venue": 1.1, "consensus": 0.6},
            "helper_pack": {"enabled": True, "helper_only_if_triggered": True},
            "freeze_mode": {"veto": True},
            "lead_execution_authority": True,
        },
    },
}
