#!/usr/bin/env bash
set -uo pipefail

ROOT="${1:-/home/z/z}"
SHA="${2:-}"
TMP=""
SEM_LOG=""
PLAN_LOG=""

cleanup() {
  [[ -n "$TMP" && -d "$TMP" ]] && rm -rf "$TMP"
}
trap cleanup EXIT

printf '%s\n' \
  'R7A4D2_SHORT_TARGET_REFRESH_AND_PLAN_START' \
  'MODE=READ_ONLY_SEMANTIC_REFRESH_THEN_SHORT_PLAN' \
  'HISTORICAL_SIMULATION_REEXECUTION_ALLOWED=false' \
  'EVENT_REPLAY_2880_ALLOWED=false' \
  'PRODUCTION_ADAPTER_MUTATION_ALLOWED=false' \
  'STRATEGY_MUTATION_ALLOWED=false' \
  'REGISTRY_MUTATION_ALLOWED=false' \
  'CONFIG_MUTATION_ALLOWED=false' \
  'ROUTER_MUTATION_ALLOWED=false' \
  'SERVICE_MUTATION_ALLOWED=false' \
  'SHADOW_START_ALLOWED=false' \
  'PAPER_LIVE_ORDER_ALLOWED=false'

if [[ -z "$SHA" ]] || ! git -C "$ROOT" cat-file -e "$SHA^{commit}" 2>/dev/null; then
  echo 'STATE=HOLD_SHORT_TARGET_REFRESH'
  echo 'BLOCKER_COUNT=1'
  echo 'BLOCKERS=["TARGET_SHA_INVALID"]'
  echo 'RC=2'
  exit 2
fi

TMP="$(mktemp -d /tmp/r7a4d2-short-refresh.XXXXXX)" || exit 2
SEM_LOG="$TMP/semantic_refresh.log"
PLAN_LOG="$TMP/short_plan.log"

bash <(git -C "$ROOT" show "$SHA:tools/bootstrap_r7a4d_semantic_parity_audit.sh") \
  "$ROOT" "$SHA" 2>&1 | tee "$SEM_LOG"
SEM_RC=${PIPESTATUS[0]}

field() {
  local key="$1"
  awk -F= -v key="$key" '$1 == key {value=$2} END {print value}' "$SEM_LOG"
}

SEM_STATE="$(field STATE)"
SEM_BLOCKERS="$(field BLOCKER_COUNT)"
SEM_ADAPTER_ERRORS="$(field ADAPTER_ERROR_COUNT)"
SEM_PAYLOAD_MISMATCH="$(field DIRECT_PAYLOAD_MISMATCH_COUNT)"
SEM_LONG_MISMATCH="$(field LONG_MAPPING_MISMATCH_COUNT)"
SEM_CRITICAL_PAYLOAD="$(field CRITICAL_PAYLOAD_MISSING_COUNT)"
SEM_PARITY_FAIL="$(field SEMANTIC_PARITY_FAILURE_STRATEGY_COUNT)"
SEM_UNEXPLAINED_ZERO="$(field UNEXPLAINED_ZERO_TRADE_STRATEGY_COUNT)"
SEM_SHORT_GAP="$(field SHORT_SCOPE_GAP_STRATEGY_COUNT)"
SEM_SHORT_DOWNGRADES="$(field SHORT_DOWNGRADE_COUNT)"

REFRESH_ERRORS=()
[[ "$SEM_STATE" == "HOLD_LONG_ONLY_SCOPE_CONFIRMED" ]] || REFRESH_ERRORS+=("SEMANTIC_STATE_INVALID:${SEM_STATE:-missing}")
[[ "$SEM_BLOCKERS" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_BLOCKER_PRESENT:${SEM_BLOCKERS:-missing}")
[[ "$SEM_ADAPTER_ERRORS" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_ADAPTER_ERROR_PRESENT:${SEM_ADAPTER_ERRORS:-missing}")
[[ "$SEM_PAYLOAD_MISMATCH" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_PAYLOAD_MISMATCH_PRESENT:${SEM_PAYLOAD_MISMATCH:-missing}")
[[ "$SEM_LONG_MISMATCH" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_LONG_MAPPING_MISMATCH_PRESENT:${SEM_LONG_MISMATCH:-missing}")
[[ "$SEM_CRITICAL_PAYLOAD" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_CRITICAL_PAYLOAD_PRESENT:${SEM_CRITICAL_PAYLOAD:-missing}")
[[ "$SEM_PARITY_FAIL" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_PARITY_FAILURE_PRESENT:${SEM_PARITY_FAIL:-missing}")
[[ "$SEM_UNEXPLAINED_ZERO" == "0" ]] || REFRESH_ERRORS+=("SEMANTIC_UNEXPLAINED_ZERO_PRESENT:${SEM_UNEXPLAINED_ZERO:-missing}")
[[ "$SEM_SHORT_GAP" =~ ^[0-9]+$ && "$SEM_SHORT_GAP" -gt 0 ]] || REFRESH_ERRORS+=("SHORT_SCOPE_GAP_EMPTY_OR_INVALID:${SEM_SHORT_GAP:-missing}")
[[ "$SEM_SHORT_DOWNGRADES" =~ ^[0-9]+$ && "$SEM_SHORT_DOWNGRADES" -gt 0 ]] || REFRESH_ERRORS+=("SHORT_DOWNGRADE_EMPTY_OR_INVALID:${SEM_SHORT_DOWNGRADES:-missing}")
[[ "$SEM_RC" == "2" ]] || REFRESH_ERRORS+=("SEMANTIC_RC_UNEXPECTED:${SEM_RC}")

if (( ${#REFRESH_ERRORS[@]} > 0 )); then
  echo 'STATE=HOLD_SHORT_TARGET_REFRESH'
  echo "BLOCKER_COUNT=${#REFRESH_ERRORS[@]}"
  printf 'BLOCKERS=['
  for i in "${!REFRESH_ERRORS[@]}"; do
    (( i > 0 )) && printf ','
    printf '"%s"' "${REFRESH_ERRORS[$i]}"
  done
  printf ']\n'
  echo 'NEXT_STAGE=R7.A4D2_SHORT_TARGET_REFRESH_AND_PLAN'
  echo 'RC=2'
  exit 2
fi

echo 'SEMANTIC_REFRESH_ACCEPTED=true'
echo "REFRESHED_SHORT_SCOPE_GAP_STRATEGY_COUNT=$SEM_SHORT_GAP"
echo "REFRESHED_SHORT_DOWNGRADE_COUNT=$SEM_SHORT_DOWNGRADES"

bash <(git -C "$ROOT" show "$SHA:tools/bootstrap_r7a4d2_short_execution_harness_plan.sh") \
  "$ROOT" "$SHA" 2>&1 | tee "$PLAN_LOG"
PLAN_RC=${PIPESTATUS[0]}
PLAN_STATE="$(awk -F= '$1 == "STATE" {value=$2} END {print value}' "$PLAN_LOG")"
PLAN_BLOCKERS="$(awk -F= '$1 == "BLOCKER_COUNT" {value=$2} END {print value}' "$PLAN_LOG")"
PLAN_TARGETS="$(awk -F= '$1 == "SHORT_TARGET_STRATEGY_COUNT" {value=$2} END {print value}' "$PLAN_LOG")"

if [[ "$PLAN_RC" != "0" || "$PLAN_STATE" != "PASS_SHORT_EXECUTION_HARNESS_PLAN" || "$PLAN_BLOCKERS" != "0" ]]; then
  echo 'STATE=HOLD_SHORT_EXECUTION_HARNESS_PLAN'
  echo 'BLOCKER_COUNT=1'
  echo "BLOCKERS=[\"SHORT_PLAN_FAILED:rc=${PLAN_RC}:state=${PLAN_STATE:-missing}:blockers=${PLAN_BLOCKERS:-missing}\"]"
  echo 'NEXT_STAGE=R7.A4D2_SHORT_TARGET_REFRESH_AND_PLAN'
  echo 'RC=2'
  exit 2
fi

if [[ "$PLAN_TARGETS" != "$SEM_SHORT_GAP" ]]; then
  echo 'STATE=HOLD_SHORT_EXECUTION_HARNESS_PLAN'
  echo 'BLOCKER_COUNT=1'
  echo "BLOCKERS=[\"REFRESHED_TARGET_COUNT_MISMATCH:${PLAN_TARGETS:-missing}:${SEM_SHORT_GAP}\"]"
  echo 'NEXT_STAGE=R7.A4D2_SHORT_TARGET_REFRESH_AND_PLAN'
  echo 'RC=2'
  exit 2
fi

echo 'STATE=PASS_SHORT_TARGET_REFRESH_AND_PLAN'
echo 'BLOCKER_COUNT=0'
echo "SHORT_TARGET_STRATEGY_COUNT=$PLAN_TARGETS"
echo "OBSERVED_SHORT_DOWNGRADE_COUNT=$SEM_SHORT_DOWNGRADES"
echo 'SEMANTIC_PROOF_REFRESHED=true'
echo 'PRODUCTION_ADAPTER_MUTATION_ALLOWED=false'
echo 'FULL_3600_REEXECUTION_ALLOWED=false'
echo 'EVENT_REPLAY_2880_ALLOWED=false'
echo 'NEXT_STAGE=R7.A4D2_SHORT_EXECUTION_HARNESS_MINIMAL_PATCH'
echo 'R7A4D2_SHORT_TARGET_REFRESH_AND_PLAN_COMPLETE'
echo 'RC=0'
exit 0
