"""Serial B trials on sealed native1h BTC/ETH DEV only; no collectors."""
import argparse
from copy import deepcopy
from datetime import datetime,timezone
import fcntl
import gzip
import json
from pathlib import Path
import os
from backend.research.rebuild import top5_mechanism_a_v1 as a
from backend.research.rebuild import top5_native_finite_runner_v1 as n

ROOT,old,metrics=a.ROOT,a.old,a.metrics
OUTPUT='research/development_evidence/TOP5_MECHANISM_B_20260907_V1'
SPEC=OUTPUT+'/SPEC.json'
NATIVE=old.OUTPUT+'/native_1h'
ORDER=['TPR1','TBR1']
CODE=['backend/research/rebuild/'+x+'_v1.py' for x in ('top5_native_finite_runner','top5_mechanism_b','test_top5_mechanism_b')]
AUTH={**a.AUTH,'prior37_preserved':True}
RULE='Native1h exact Primary/Broad signals regenerated by existing owner with no-trade admission capture; identical saved raw intents. Actual next-open entry and native SL first/TP second each bar, native timeout=entry_i+48 close. At original timeout-1 alive, side-price-profit>0 AND native direction/line/EMA50/slope trend permits exactly48 more bars. Extension only: loss of that trend queues next observed open before later HLC, including gap (existing top5_no_credit_exit RULE); final cap=entry_i+96 close after native SL/TP. Native actual exit-bar-open+cooldown ownership, no synthetic D clock or old exit preinput. Boundary completion timestamp==end remains censored; known boundary native SL/TP proxy retained at original proxy price as censored completion-time observation; boundary timeout is unfilled and marked at last close like ordinary unfinished. No dropped loss or forced market liquidation. Native trailing flags remain unimplemented. FIXED may overlap; FULL actual ownership/cooldown. All original costs plus20bps floor; whole-cost2. No actual account sizing.'


def authorize():
    a.authorize();c=old.read(SPEC);old.probe.verify_seal(c,'MECHANISM_B_SPEC')
    if c['rule']!=RULE or c['order']!=ORDER or c['goals']!=metrics.exits.GOAL or set(c['code_files_sha256'])!=set(CODE):
        raise RuntimeError('B_FROZEN_RULE_CODE_DRIFT')
    if c['budget']!={'prior':37,'new_max':2,'total_after_max':39} or c['new_outcomes_seen_at_freeze'] is not False:
        raise RuntimeError('B_BUDGET_DRIFT')
    for k,v in AUTH.items():
        if c.get(k)!=v:raise RuntimeError('B_AUTHORITY:'+k)
    for p,h in {**c['code_files_sha256'],**c['preserved_files_sha256'],**c['ci_files_sha256']}.items():
        if old.file_sha(ROOT/p)!=h:raise RuntimeError('B_FROZEN_BYTES:'+p)
    return c


def load_inputs(c):
    p=old.read(old.POLICY)
    dev=a.account.source.inputs.require_development(old.read(old.probe.STAGE),ROOT)
    if dev['receipt_sha256']!=c['cost_sha256'] or p['cost_binding_sha256']!=c['cost_sha256']:
        raise RuntimeError('B_COST_AUTHORITY')
    manifest=old.read(NATIVE+'/manifest.json');old.probe.verify_seal(manifest,'NATIVE_MANIFEST')
    start,end=c['calendar']
    if manifest['development_interval_ms']!=[start,end] or manifest['interval_ms']!=n.HOUR:
        raise RuntimeError('B_NATIVE_CALENDAR')
    rows={}
    for symbol in c['symbols']:
        path=ROOT/NATIVE/(symbol+'.json.gz')
        if old.file_sha(path)!=manifest['symbols'][symbol]['file_sha256']:raise RuntimeError('B_NATIVE_SHA')
        data=json.loads(gzip.decompress(path.read_bytes()));n.native.validate_native(data,start,end)
        rows[symbol]=[dict(r,bar_open_ts=r['ts_ms'],bar_close_ts=r['ts_ms']+n.HOUR) for r in data]
    return p,{s:dev['cost_by_symbol'][s] for s in c['symbols']},rows


def charge(raw,symbol,kind,stage,policy,costs,rows):
    out=a.account.charge_result(raw,symbol,n.LANES[kind],stage,policy,costs,rows)
    for key,seal in [('trades','trade_sha256'),('open_observations','observation_sha256')]:
        for t in out[key]:
            t.pop(seal,None);t['native_interval_ms']=n.HOUR;t['candidate_id']=n.RULES[kind]
            t['evidence_type']='REUSED_NATIVE1H_DEV_TIMEOUT_ONLY';t[seal]=old.digest(t)
    return out


def replay(kind,rows,bundles,policy,costs,enabled=True,fixed=None):
    out={k:[] for k in ('trades','open_observations','events','trace')};out['admission']={}
    for symbol,rr in sorted(rows.items()):
        cache,tape,_=bundles[symbol]
        raw=n.replay(rr,tape,cache,enabled=enabled,fixed_indices=None if fixed is None else fixed[symbol])
        v=charge(raw,symbol,kind,'CANDIDATE' if enabled else 'P',policy,costs,rr)
        for key in ('trades','open_observations','events','trace'):out[key].extend(v[key])
        out['admission'][symbol]=raw['audit']
    return out


def verify_parent(kind,parent,tapes):
    source=a.account.source.inputs
    saved=[t for t in source.read_lines(ROOT/old.OUTPUT/'baseline/trades.jsonl.gz') if t['lane_id']==n.LANES[kind]]
    key=lambda t:(t['symbol'],t['signal_ts'],t['side'])
    p,b=({key(t):t for t in seq} for seq in (parent['trades'],saved))
    if p.keys()!=b.keys():raise RuntimeError('B_STORED_CLOSED_ORIGINS')
    for origin in p:
        for f in ('entry_ts','entry_price','exit_ts','exit_price','side','gross_bps','net_bps','cost_bps','funding_bps','hold_ms','exit_reason'):
            if p[origin][f]!=b[origin][f]:raise RuntimeError('B_STORED_CLOSED_PARITY:'+f)
    old_tape=[e for e in source.read_lines(ROOT/old.OUTPUT/'baseline/events.jsonl.gz') if e['lane_id']==n.LANES[kind]]
    project=lambda seq:sorted([{f:e[f] for f in n.FIELDS} for e in seq],key=lambda e:(e['symbol'],e['signal_index']))
    if project(old_tape)!=project([e for _,events,_ in tapes.values() for e in events]):
        raise RuntimeError('B_NATIVE_SIGNAL_INTENT_DRIFT')
    return {'closed_exact_parity_T':len(p),'raw_intent_exact_parity_T':len(old_tape),
            'restored_censored_T':len(parent['open_observations']),
            'original_closed_ledger_unchanged':True,'tail_not_multiple_live_positions':True}


def run(kind,verify=False):
    c=authorize();out=ROOT/OUTPUT/kind;out.mkdir(parents=True,exist_ok=True)
    ap=out/'ATTEMPT.json';rp=out/'receipt.json'
    if not verify and (ap.exists() or rp.exists()):a.log('DUPLICATE_NO_OP',candidate=kind);return None
    if verify and not rp.exists():raise RuntimeError('B_MISSING_COMMITTED_RECEIPT')
    p,costs,rows=load_inputs(c);start,end=c['calendar']
    if not verify:
        used=[k for k in ORDER if (ROOT/OUTPUT/k/'ATTEMPT.json').exists()]
        if kind!=ORDER[len(used)]:raise RuntimeError('B_SERIAL_ORDER')
        marker=old.seal({'candidate':kind,'ordinal':38+len(used),'spec_seal':c['receipt_sha256'],
            'utc':datetime.now(timezone.utc).isoformat(),'pid':os.getpid(),'before_first_new_market_path':True,
            'github_run_id':os.environ.get('GITHUB_RUN_ID'),'failed_run_consumes_trial':True})
        old.probe.write_immutable(ap,old.probe.canonical(marker))
    else:
        marker=old.read(str(ap.relative_to(ROOT)));old.probe.verify_seal(marker,'B_ATTEMPT')
        if marker['spec_seal']!=c['receipt_sha256']:raise RuntimeError('B_ATTEMPT_BINDING')
    a.log('EXACT_REPRODUCTION_START' if verify else 'NEW_CANDIDATE_START',candidate=kind,ordinal=marker['ordinal'])
    policy={**p,'batch_id':Path(OUTPUT).name,'receipt_sha256':c['receipt_sha256'],'code_files_sha256':c['code_files_sha256'],
            'combined_data_sha256':c['native_data_sha256'],'development_interval_ms':[start,end]}
    bundles={symbol:n.prepare(rr,symbol,kind,start,end,c['native_policy_sha256'][kind]) for symbol,rr in rows.items()}
    with old.probe.io_boundary([],out):
        parent=replay(kind,rows,bundles,policy,costs,enabled=False)
        origins={symbol:[t['signal_index'] for key in ('trades','open_observations') for t in parent[key] if t['symbol']==symbol] for symbol in rows}
        fixed=replay(kind,rows,bundles,policy,costs,fixed=origins)
        full=replay(kind,rows,bundles,policy,costs)
    parity=verify_parent(kind,parent,bundles)
    if metrics.index(parent).keys()!=metrics.index(fixed).keys():raise RuntimeError('B_FIXED_ENTRY_SET')
    views={'P':parent,'FIXED':fixed,'FULL':full}
    with n.reporting():
        stages={name:metrics.exits.build_stage(v['trades'],v['open_observations'],v['events'],rows,costs,policy,c['symbols'],start,end) for name,v in views.items()}
        comparisons={name:metrics.exits.compare(stages['P'],stages[name],parent['trades'],parent['open_observations'],
            views[name]['trades'],views[name]['open_observations'],rows,costs,start,end) for name in ('FIXED','FULL')}
    effects={'P':metrics.effects(parent,full)};bridge=metrics.fixed_full_bridge(parent,fixed,full)
    values={k:metrics.stage_values(v) for k,v in stages.items()}
    doc={'candidate':kind,'period':'DEV2025','views':views,'stages':stages,'comparisons':comparisons,
         'effects':effects,'fixed_full_bridge':bridge,'values':values,'parent_parity':parity}
    path=out/'DEV2025.json.gz';raw=old.probe.canonical(doc);payload=path.read_bytes() if path.exists() else gzip.compress(raw,mtime=0)
    if gzip.decompress(payload)!=raw:raise RuntimeError('B_EXACT_REPLAY_DRIFT')
    old.probe.write_immutable(path,payload,verify_only=verify)
    compact=deepcopy(effects);compact['P'].pop('per_origin')
    result={'values':values,'decisions':{k:v['decision'] for k,v in comparisons.items()},'effects':compact,
        'occupancy_bridge_summary':bridge['terminal'],'uncertainty':{k:v['uncertainty'] for k,v in comparisons.items()},
        'concentration':{k:{'profit':v['metrics']['concentration'],'weekly':v['diagnostics']['weekly_clusters']} for k,v in stages.items()},
        'partial_assets':{'preserve_development_evidence':True,'formal_or_operating_adoption':False},'admission':full['admission']}
    receipt=old.seal({**AUTH,'candidate':kind,'candidate_ordinal':marker['ordinal'],'spec_seal':c['receipt_sha256'],
        'parent_id':c['parents'][kind],'parent_parity':parity,'results':{'DEV2025':result},
        'SEEN2026':{'status':'NOT_RUN','reason':'NATIVE1H_SOURCE_NOT_FOUND_NO_COLLECTOR_AUTHORIZED','slot_consumed':False},
        'artifacts':{'DEV2025':{'path':str(path.relative_to(ROOT)),'file_sha256':old.file_sha(path)}},
        'execution_inventory':{'native_intent_capture_no_market_paths':2,'new_native_parent_baseline':1,'FIXED':1,'FULL':1},
        'decoded_after_20260905':0,'native_rows':{k:len(v) for k,v in rows.items()}})
    old.probe.write_immutable(rp,old.probe.canonical(receipt),verify_only=verify)
    text=a.prior.report(receipt).replace(b'Q0 daily marks revalued exactly without replaying its signals.',b'Native closed parents match stored ledgers; strict-end censored observations explicitly restored.')
    old.probe.write_immutable(out/'RESULTS.md',text,verify_only=verify)
    a.log('COMPLETE',candidate=kind,seal=receipt['receipt_sha256'],values=values,decisions=result['decisions'])
    return receipt


def main():
    p=argparse.ArgumentParser();p.add_argument('--candidate',choices=ORDER);p.add_argument('--check-only',action='store_true');p.add_argument('--verify-only',action='store_true');args=p.parse_args()
    if args.check_only:a.log('B_FREEZE_PASS',seal=authorize()['receipt_sha256']);return
    if not args.candidate:p.error('candidate required')
    with Path('/tmp/top5-mechanism-sole-writer.lock').open('w') as f:
        fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB)
        try:run(args.candidate,args.verify_only)
        except Exception as exc:a.log('FAILED',candidate=args.candidate,error=repr(exc));raise


if __name__=='__main__':main()
